### ISSUE TITLE
Lidar render error

### ISSUE THREAD

**Issue by aapeng-s** [OpenAVP/CARLA-Dataset#15]
when I try to render lidar data,there is an error.
![2024-10-28 17-24-30 的屏幕截图](https://github.com/user-attachments/assets/d254d6c6-60b3-4f9f-9e04-719f7afcecff)

**Comment by aapeng-s** [comment]
when I use shape(4),the lidar data can be read.Maybe there is a  bug in lidar data format.
![2024-10-28 21-51-17 的屏幕截图](https://github.com/user-attachments/assets/8345c706-17f6-42f6-aa3d-68b078c74157)

**Comment by ZHAO-ZIRUI** [comment]
Maybe missing ring index

**Comment by suayu** [comment]
之前统一的中间格式，LIDAR相关格式为:(x y z intensity),见群内文件"ndarray格式说明.txt"。

**Comment by ZHAO-ZIRUI** [comment]
我回顾了一下代码，`bind.actor.data.content` 是一个 `shape: [n, 5] @ np.float64` 的数据。

其中数据分别为 `x, y, z, seg_id, obj_id`，虽然与这里要求的点云格式不符，但是数据形式是一致的。

考虑是否因为在读取数据时指定了 `dtype=np.float32` 引起的问题。

关于点云格式不符的问题将会继续修正

**Comment by aapeng-s** [comment]
雷达数据必须为float32,可以考虑下面的改动
296`        data1 = data.astype(np.float32) #use temp data1 to avoid change to data`
297`        data1.tofile(path)`
