### ISSUE TITLE
Database error in sample_annotation

### ISSUE THREAD

**Issue by aapeng-s** [OpenAVP/CARLA-Dataset#9]
sample_annotation中translation,size,rotation生成的字段类型为str，而不是列表。
Lidar数据的文件夹名字是Semantic_Lidar,原始数据集为LIDAR_TOP,但是nuscenes部分函数会检测文件夹的名称，出现No LIDAR_TOP in data的报错

**Comment by ZHAO-ZIRUI** [comment]
Note: there are actually **two** different issues!

**Comment by ZHAO-ZIRUI** [comment]
> Note: there are actually **two** different issues!

See #11
